### PR TITLE
Mavenlink - v4.1.4

### PR DESCRIPTION
**Pull request by shirish-pampoorickal**
[Build Status](https://travis-ci.org/mavenlink/delayed_job_active_record)

Merges https://github.com/collectiveidea/delayed_job_active_record/tree/v4.1.4 with #2

### CODE REVIEW

**Review by brandonduff — APPROVED** [review]
If this is just merging those two and works with bigmaven, lgtm

**Comment by diclophis** [comment]
@shirish-pampoorickal / @brandonduff what do we want to do with this PR, is it possible to get this merged, or has it been superseded by other PRs?

**Comment by brandonduff** [comment]
I _think_ this has been superseded. Gemfile is currently pointing at `git: 'https://github.com/mavenlink/delayed_job_active_record', branch: 'mavenlink-4_1_3_lock'`. I don't really remember this.

**Comment by diclophis** [comment]
closing in favour of https://github.com/collectiveidea/delayed_job_active_record/pull/202

**Pull request closed without merging**
